### ISSUE TITLE
Problem with new namespace autocompletion

### ISSUE THREAD

**Issue by devantler** [AdrianWilczynski/NamespaceAutocompletion#2]
When I create a new namespace with the C# snippet, I have to click away from the auto focus, on the namespace name, for namespace autocompletion to occur. This Is a mild annoyance, as it would be cool to create a new namespace, and immediately have this extension recognize the namespace for autocompletion.

Edit: This is a problem when typing the full namespace, haven't tried namespace-fill, which might work just fine.

**Comment by AdrianWilczynski** [comment]
Hi,
Sorry for not responding earlier. I didn't notice this issue 😳

I think it's really just how VSCode works. I'm not getting autcompletion from official C# extension in snippets either.

Good thing is that you don't have to click away, you can pull up autocompletion list (without existing the snippet) by pressing `Ctrl` + `Space`.

**Comment by devantler** [comment]
@AdrianWilczynski that's okay :-) 

Thank you for the suggestion, I'll try to make a habit of activating autocompletion manually in this case.
